// Run against npm run dev -- --port 4187 with:
// ~/.local/bin/tabbit-cli nodejs --task bdi-dialog-tests --request-id dialogs-01 < scripts/test-dialogs.tabbit.js
const baseURL = 'http://127.0.0.1:4187';
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await page.goto(baseURL, { waitUntil: 'networkidle' });
await page.setViewportSize({ width: 1280, height: 900 });
async function openProject() {
  await page.locator('.pen-file-menu > summary').click();
  await page.getByRole('menuitem', { name: '新建皮肤', exact: true }).click();
  await expect(page.locator('#new-project-dialog')).toBeVisible();
}
await openProject();
const project = page.locator('#new-project-dialog');
await expect(project.locator('.template-preview.is-rendered')).toHaveCount(7, { timeout: 30000 });
await project.getByLabel('文件名称', { exact: true }).fill('../invalid');
await project.getByRole('button', { name: '创建皮肤', exact: true }).click();
await expect(project).toBeVisible();
expect(await project.locator('[name=project-name]').evaluate(node => node.validity.valid)).toBe(false);
await project.getByRole('button', { name: '取消', exact: true }).click();
await expect(project).not.toBeVisible();
await openProject();
await project.getByLabel('文件名称', { exact: true }).fill('界面回归测试');
await project.locator('input[value=official-android-bds]').check();
await expect(project.locator('.project-extension')).toHaveText('.bds');
await project.getByRole('button', { name: '创建皮肤', exact: true }).click();
await expect(page.locator('#document-name')).toContainText('界面回归测试.bds', { timeout: 30000 });
await page.getByRole('button', { name: '编辑模式', exact: true }).click();
await page.locator('#preview').click({ position: { x: 220, y: 120 } });
await page.locator('#quick-inspector').getByRole('button', { name: '样式', exact: true }).click();
const trigger = page.locator('.style-picker-state:visible').first();
const input = trigger.locator('xpath=ancestor::*[contains(@class,"style-reference-input")]').locator('input').first();
const original = await input.inputValue();
await trigger.click();
const library = page.locator('#style-picker-dialog');
await expect(library.locator('[data-style-library-mode=styles]')).toHaveAttribute('aria-pressed', 'true');
await expect(library.locator('.style-picker-item').first()).toBeVisible();
const total = await library.locator('.style-picker-item').count();
expect(total).toBeGreaterThan(10);
await library.locator('[data-style-library-filter=key]').click();
await expect(library.locator('[data-style-library-filter=key]')).toHaveAttribute('aria-pressed', 'true');
await expect.poll(() => library.locator('.style-picker-item').count()).toBeLessThan(total);
await library.locator('[data-style-library-filter=all]').click();
await expect(library.locator('.style-picker-item')).toHaveCount(total);
await library.locator('.style-picker-item').first().click();
await expect(page.locator('#style-library-preview')).toBeVisible();
await expect(input).toHaveValue(original);
await library.getByLabel('搜索样式或图片').fill('no-such-style');
await expect(page.locator('#style-picker-empty')).toBeVisible();
await expect(library.locator('.style-picker-item')).toHaveCount(0);
await library.getByLabel('搜索样式或图片').fill('#1');
await expect(library.locator('.style-picker-item').first()).toBeVisible();
await library.locator('.style-picker-item').first().dblclick();
await expect(library).not.toBeVisible();
await expect(input).toHaveValue('1');
await trigger.click();
await library.getByRole('button', { name: '全部图片', exact: true }).click();
await expect(library.locator('.style-picker-item img').first()).toBeVisible();
await expect.poll(() => library.locator('.style-picker-item img').evaluateAll(nodes => nodes.every(n => n.complete && n.naturalWidth > 0))).toBe(true);
await library.locator('.style-picker-item').first().click();
await expect(page.locator('#style-library-preview')).toBeVisible();
await library.getByRole('button', { name: '选择切片并应用', exact: true }).click();
await expect(library).not.toBeVisible();
await expect(page.locator('#style-image-dialog')).toBeVisible();
await expect(page.locator('#style-image-picker-canvas')).toBeVisible();
await page.keyboard.press('Escape');
await trigger.click();
await expect(library.locator('[data-style-library-mode=styles]')).toHaveAttribute('aria-pressed', 'true');
await page.setViewportSize({ width: 390, height: 844 });
expect(await library.evaluate(n => n.scrollWidth <= n.clientWidth)).toBe(true);
await page.keyboard.press('Escape');
await expect(library).not.toBeVisible();
await page.setViewportSize({ width: 1280, height: 900 });
await openProject();
await page.setViewportSize({ width: 390, height: 844 });
expect(await project.evaluate(n => n.scrollWidth <= n.clientWidth)).toBe(true);
await expect(project.getByRole('button', { name: '创建皮肤', exact: true })).toBeInViewport();
await page.keyboard.press('Escape');
expect(errors).toEqual([]);
return { passed: true, styles: total, checks: ['7 template previews', 'invalid name and cancel', 'create and rename BDS', 'categories', 'preview does not mutate', 'empty search', 'double-click applies', 'images load', 'image slice chooser', 'default tab reset', '390px layout', 'Escape closes', 'no page errors'] };
