// Run against npm run dev -- --port 4187 with:
// ~/.local/bin/tabbit-cli nodejs --task bdi-dialog-tests --request-id bda-01 < scripts/test-dialogs-bda.tabbit.js
await page.goto('http://127.0.0.1:4187/', { waitUntil: 'networkidle' });
await page.setViewportSize({ width: 1280, height: 900 });
await page.locator('.pen-file-menu > summary').click();
await page.getByRole('menuitem', { name: '新建皮肤', exact: true }).click();
await page.locator('#new-project-dialog input[value=default-android]').check();
await page.locator('#new-project-dialog').getByRole('button', { name: '创建皮肤', exact: true }).click();
await expect(page.locator('#document-name')).toContainText('.bda', { timeout: 30000 });
await page.getByRole('button', { name: '编辑模式', exact: true }).click();
await page.locator('#preview').click({ position: { x: 220, y: 120 } });
await page.locator('#quick-inspector').getByRole('button', { name: '样式', exact: true }).click();
const trigger = page.getByRole('button', { name: '背景样式：点击更换样式，Command/Ctrl 点击编辑样式', exact: true });
await trigger.click();
const library = page.locator('#style-picker-dialog');
await expect(library.locator('.style-picker-item').first()).toBeVisible();
await library.locator('.style-picker-item').last().click();
await expect(page.locator('#style-library-apply')).toBeDisabled();
await expect(page.locator('#style-library-apply')).toHaveText('样式类型不兼容');
await library.getByRole('button', { name: '全部图片', exact: true }).click();
await expect(library.locator('.style-picker-item img').first()).toBeVisible();
const image = await library.locator('.style-picker-item strong').first().innerText();
await library.locator('.style-picker-item').first().click();
await page.locator('#style-library-apply').click();
await expect(library).not.toBeVisible();
await trigger.click();
await library.getByRole('button', { name: '全部图片', exact: true }).click();
await expect(library.locator('.style-picker-item.selected strong', { hasText: image }).first()).toBeVisible();
await page.setViewportSize({ width: 390, height: 844 });
expect(await library.evaluate(n => n.scrollWidth <= n.clientWidth)).toBe(true);
await page.keyboard.press('Escape');
const standalone = await context.newPage();
const errors = [];
standalone.on('pageerror', error => errors.push(error.message));
await standalone.goto('http://127.0.0.1:4187/new-project.html', { waitUntil: 'networkidle' });
await standalone.setViewportSize({ width: 390, height: 650 });
await expect(standalone.locator('.template-preview.is-rendered')).toHaveCount(7, { timeout: 30000 });
expect(await standalone.locator('form').evaluate(n => n.scrollWidth <= n.clientWidth && getComputedStyle(n).display === 'grid')).toBe(true);
await expect(standalone.getByRole('button', { name: '创建皮肤', exact: true })).toBeInViewport();
await standalone.getByRole('button', { name: '创建皮肤', exact: true }).click();
await expect(standalone.locator('#project-error')).toBeVisible();
await expect(standalone.getByRole('button', { name: '创建皮肤', exact: true })).toBeEnabled();
expect(errors).toEqual([]);
await standalone.close();
return { passed: true, checks: ['BDA incompatible style blocked', 'BDA image update persisted', 'narrow image grid', 'standalone previews and CSS', 'standalone failure restores controls'] };
