const fs = await import('node:fs/promises');
await page.goto('http://127.0.0.1:4189/', { waitUntil: 'networkidle' });
await page.setViewportSize({ width: 1440, height: 1000 });
await page.locator('#browser-open').setInputFiles({ name: '3花季-IOS.bda', mimeType: 'application/octet-stream', buffer: await fs.readFile('/Users/kaze/work/bd/3花季-IOS.bda') });
await expect(page.locator('#bda-config-fields')).toHaveAttribute('data-bda-scope', 'panel', { timeout: 30000 });
const close = page.locator('#file-operation-dialog[open]').getByRole('button', { name: '关闭', exact: true });
if (await close.isVisible()) await close.click();
await page.getByRole('button', { name: '编辑模式', exact: true }).click();
await expect(page.locator('[data-document-key=NO_BLUR]')).toHaveCount(0);
const blur = page.getByRole('switch', { name: '背景模糊', exact: true });
const original = await blur.isChecked();
await blur.setChecked(!original);
await expect(page.getByRole('switch', { name: '背景模糊', exact: true })).toBeChecked({ checked: !original });
await page.getByRole('switch', { name: '背景模糊', exact: true }).setChecked(original);
await page.locator('#preview').click({ position: { x: 240, y: 60 } });
await expect(page.locator('.key-layout-fields')).not.toBeVisible();
await expect(page.locator('.key-gesture-fields')).not.toBeVisible();
await expect(page.locator('#mobile-inspector-groups').getByRole('button', { name: '布局', exact: true })).toHaveCount(0);
await page.locator('#mobile-inspector-groups').getByRole('button', { name: '样式', exact: true }).click();
await expect(page.locator('#bda-config-fields')).toHaveAttribute('data-bda-scope', 'key');
await expect(page.getByRole('switch', { name: '背景模糊', exact: true })).toHaveCount(0);
await expect(page.locator('.key-appearance-fields')).not.toBeVisible();
await page.locator('[data-bda-inspector-state=pressed]').click();
await expect(page.locator('[data-bda-inspector-state=pressed]')).toHaveAttribute('aria-pressed', 'true');
await page.locator('[data-bda-inspector-state=normal]').click();
const style = page.locator('#bda-config-fields .bda-style-reference-preview').first();
await expect(style).toBeVisible();
await style.click();
await expect(page.locator('#style-picker-dialog')).toBeVisible();
await page.keyboard.press('Escape');
await page.setViewportSize({ width: 390, height: 844 });
await page.locator('[data-mobile-pane=inspector]').first().click();
expect(await page.locator('#quick-inspector').evaluate(n => n.scrollWidth <= n.clientWidth)).toBe(true);
await page.setViewportSize({ width: 1440, height: 1000 });
return { passed: true, checks: ['iOS BDA imported', 'BDA panel flags', 'panel/key separation', 'no INI appearance controls', 'normal/pressed state', 'style picker', '390px overflow'], screenshot: await page.screenshot({ path: artifactPath('bda-key-right-sidebar.png') }) };
