// Run with ~/.local/bin/tabbit-cli nodejs --task inspector-redesign < scripts/test-inspector.tabbit.js
await page.goto('http://127.0.0.1:1420', {waitUntil:'networkidle'});
await page.setViewportSize({width:1280,height:900});
await page.locator('.template-card[data-template="official-android-bds"]').click();
await expect(page.locator('#quick-inspector')).toBeVisible({timeout:30000});
await page.getByRole('button',{name:'编辑模式',exact:true}).click();
await page.locator('#preview').click({position:{x:220,y:120}});
await expect(page.locator('#inspector-multi-layout')).not.toBeVisible();
await expect(page.locator('#inspector-search')).toHaveCount(0);
await page.locator('#mobile-inspector-groups').getByRole('button',{name:'样式',exact:true}).click();
await expect(page.locator('[data-key-field=FORE_OFFSET]')).not.toBeVisible();
await page.locator('.appearance-layout-fields > summary').click();
await expect(page.locator('[data-key-field=FORE_OFFSET]')).toBeVisible();
const layoutTab = page.locator('#mobile-inspector-groups').getByRole('button',{name:'布局',exact:true});
await layoutTab.click();
await layoutTab.press('ArrowRight');
await expect(page.locator('#mobile-inspector-groups').getByRole('button',{name:'样式',exact:true})).toBeFocused();
await layoutTab.click();
const x = page.locator('[data-key-field=x]');
const original = await x.inputValue();
const originalBox = await x.boundingBox();
await x.fill(String(Number(original)+1));
await x.press('Tab');
await expect(x).toHaveValue(String(Number(original)+1));
expect(await x.boundingBox()).toEqual(originalBox);
await page.locator('.geometry-fields .pin-reset').click();
await expect(x).toHaveValue(original);
await expect(page.locator('.pin-actions-meta')).toHaveText('未修改');
await page.locator('#mobile-inspector-groups').getByRole('button',{name:'动作',exact:true}).click();
await expect(page.locator('.inspector-gesture-pad')).toBeVisible();
await expect(page.locator('.inspector-gesture-preview')).toHaveCount(0);
const up = page.locator('[data-key-field=UP]');
const originalUp = await up.inputValue();
const upBox = await up.boundingBox();
await up.fill('8');
await up.press('Tab');
expect(await up.boundingBox()).toEqual(upBox);
await expect(page.locator('[data-gesture=UP]')).toHaveClass(/configured/);
await page.locator('.direction-up .pin-reset').click();
await expect(up).toHaveValue(originalUp);
await expect(page.locator('[data-gesture=UP]')).toHaveClass(originalUp && originalUp !== 'None' ? /configured/ : /direction-up/)
await layoutTab.click();
await page.setViewportSize({width:390,height:844});
await page.locator('[data-mobile-pane=inspector]').first().click();
await expect(layoutTab).toBeVisible();
expect(await page.locator('#quick-inspector').evaluate(n=>n.scrollWidth <= n.clientWidth)).toBe(true);
await page.setViewportSize({width:1280,height:900});
return {passed:true,checks:['single selection hides batch tools','no search box','advanced disclosure','arrow navigation','geometry and gesture edits without layout shift','reset values','live gesture pad input','390px overflow']};
