import assert from "node:assert/strict"
import fs from "node:fs"

const main = fs.readFileSync("src/main.ts", "utf8")
const plugin = fs.readFileSync("src-tauri/native-share/android/src/main/java/SharePlugin.kt", "utf8")
const manifest = fs.readFileSync("src-tauri/native-share/android/src/main/AndroidManifest.xml", "utf8")
const html = fs.readFileSync("index.html", "utf8")
const css = fs.readFileSync("src/style.css", "utf8")

assert.match(main, /function isAndroidWeb\(\): boolean/)
assert.match(main, /function isIOSWeb\(\): boolean/)
assert.match(main, /if \(isIOSWeb\(\)\) return "bdi"/)
assert.match(main, /if \(isAndroidTauri\(\) \|\| isAndroidWeb\(\)\) return archive\?\.format === "bda" \? "bda" : "bds"/)
assert.match(main, /if \(isAndroidTauri\(\)\) \{[\s\S]*await invoke\("share_file"/)
assert.match(main, /await navigator\.share\(\{ title: name, files: \[file\] \}\)/)
assert.match(main, /if \(!picker\) \{[\s\S]*link\.download = filename[\s\S]*return filename/)
assert.doesNotMatch(main, /当前浏览器不支持系统保存/)
assert.match(plugin, /Intent\(Intent\.ACTION_VIEW\)/)
assert.doesNotMatch(plugin, /Intent\(Intent\.ACTION_SEND\)/)
assert.match(plugin, /setPackage\("com\.baidu\.input"\)/)
assert.match(plugin, /setPackage\("com\.baidu\.input_mi"\)/)
assert.match(plugin, /AlertDialog\.Builder\(activity\)/)
assert.match(plugin, /百度输入法（com\.baidu\.input）/)
assert.match(plugin, /百度输入法小米版（com\.baidu\.input_mi）/)
assert.match(plugin, /resolveActivity\(intent, PackageManager\.MATCH_DEFAULT_ONLY\)/)
assert.match(plugin, /when \(targets\.size\) \{[\s\S]*0 -> invoke\.reject[\s\S]*1 -> openSkin[\s\S]*else -> AlertDialog\.Builder/)
assert.match(plugin, /setDataAndType\(uri, args\.mimeType\)/)
assert.match(plugin, /activity\.startActivity\(viewIntent\)/)
assert.doesNotMatch(plugin, /Intent\.createChooser\(sendIntent/)
assert.match(manifest, /<package android:name="com\.baidu\.input"\s*\/>/)
assert.match(manifest, /<package android:name="com\.baidu\.input_mi"\s*\/>/)
assert.match(html, />分享皮肤<\/span>/)
assert.doesNotMatch(html, />分享到百度输入法<\/span>/)
assert.match(css, /\.mobile-command-menu\s*\{[^}]*position: static;/)
assert.match(css, /\.mobile-command-actions\s*\{[^}]*position: absolute;/)
assert.doesNotMatch(css, /\.mobile-command-actions\s*\{[^}]*position: fixed;/)

console.log("✓ 移动网页支持普通下载，iOS、Android 网页与 Android APK 使用各自的分享路径和皮肤格式")
